<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-cn">
    <title><?php echo $title ?></title>
    <body>
    <?php $this->renderWidgets('header'); ?>
    <?php $this->renderBody(); ?>
    <?php $this->renderPage('home.index'); ?>
    <?php $this->renderPage('home.index'); ?>
    <?php $this->renderPage('home.index'); ?>
    <?php $this->renderPage('home.index'); ?>
    <?php $this->renderWidgets('bottom'); ?>
    </body>
</html>