<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-cn">
    <title><?php echo $title ?></title>
    <head>
        <script src="http://localhost:84/js/jquery-1.8.2.min.js"></script>
        <script src="http://localhost:84/js/jquery.pjax.js"></script>
    </head>
    <body>
    <?php $this->renderWidgets('header'); ?>
    <?php $this->renderBody(); ?>
    <?php $this->renderWidgets('bottom'); ?>
    </body>
</html>