<?php
/**
 * Created by PhpStorm.
 * User: lbob
 * Date: 2014/12/31
 * Time: 10:04
 * @var $this \Xaircraft\Mvc\View
 */

$this->beginPjax('pjaxContainer');
$this->html()->showList($posts, array(
    'show' => array(
        'id'            => 'ID',
        'title'         => '标题',
        'author'        => '作者',
        'keyword'       => '关键字',
        'content'       => '内容',
        'update_at'     => '更新时间',
        'create_at'     => '创建时间'
    )
))->page($pageIndex, $pageCount, $recordCount)->render();
$this->endPjax('pjaxContainer');