<?php
/**
 * @var $this \Xaircraft\Mvc\View
 */
?>

<?php $this->html()->link('post/', '返回列表')->render(); ?>

<?php $this->beginPjax('pjaxContainer'); ?>
    <h1><?php echo $title ?></h1>
    <p><?php echo $post->content ?></p>
<?php $this->html()->link('/post/show/' . ($this->req->param('id') == '12' ? '11' : '12'), '1链接' . ($this->req->param('id') == '12' ? 'B' : 'A'))->render(); ?>
    <p>当前时间：<?php echo time(); ?></p>
<?php $this->endPjax('pjaxContainer'); ?>